import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Metadata } from "next";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Fullstack Auth Demo",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased w-2/3 border-x border-gray-200 mx-auto",
          fontSans.variable
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
